[package]
authors = ["Chris Paige"]
name = "host_discovery"
license = "MIT"
documentation = "https://docs.rs/host_discovery"
description = "A simple Rust crate for host discovery"
version = "1.6.3"
repository = "https://github.com/v0idmatr1x/host_discovery"
edition = "2021"

[target.'cfg(windows)'.dependencies]
winreg = "0.52.0"
