[package]
authors = ["Chris Paige"]
name = "host_discovery"
license = "MIT"
documentation = "https://docs.rs/host_discovery"
description = "A simple Rust crate for host discovery"
version = "1.7.1"
repository = "https://github.com/v0idmatr1x/host_discovery"
edition = "2021"

[features]
windows = ["dep:winreg"]

[target.'cfg(windows)'.dependencies]
winreg = { version = "0.52.0", optional = true }

[dependencies]
regex = "1.10.3"
reqwest = { version = "0.11.24", features = ["blocking"] }
